### ISSUE TITLE
Server restart logs out user

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/kazana#115]
reported by @lucidNTR, I'm looking into it

**Comment by lucidNTR** [comment]
(with backend couchdb)

**Comment by gr2m** [comment]
yes, I could reproduce it with couchdb backend. I'm looking into it today

**Comment by lucidNTR** [comment]
cool, glad i did not mess something up :-D

**Comment by lucidNTR** [comment]
@jo perfect example of what happens when the setup is not real world enough

**Comment by gr2m** [comment]
question is, which ones of the two is buggy, we had both cases already :)

I found the problem, and I can't tell which one is wrong this time. If update an existing users doc with the _same_ password, it behaves different

1. In CouchDB: it ends the user session
2. In PouchDB Server: it does not end the session

I'll ask around :)

For the time begin, @jo we could work around this problem by making the bootstrapping of docs in `_users` smart, by checking if the provided passwords are correct. If they are, we can keep the `salt` and `derived_key` etc, and do not set `password`. If the password is the same and the other properties also didn't change, we don't need to update the document at all, which is nice to have anyway.

Thoughts?

**Comment by gr2m** [comment]
filed issue on express-pouchdb: https://github.com/pouchdb/express-pouchdb/issues/268

**Comment by gr2m** [comment]
Okay, turns out PouchDB Server is wrong here: https://github.com/pouchdb/express-pouchdb/issues/268#issuecomment-154220101

So @jo, we need to make the users doc bootstrapping smarter, otherwise we will end user sessions every time we restart the server. Maybe we can add it to https://github.com/jo/couchdb-push, or make another lib for `_users` only, and use that one in https://github.com/eHealthAfrica/couchdb-bootstrap for `_users` doc, and the standard `couchdb-push` for all other DBs?

**Comment by gr2m** [comment]
@lucidNTR to work around the problem for the time being, create another user that is not part of the bootstrapped example users, then you shouldn't have that problem

**Comment by lucidNTR** [comment]
@gr2m cool thanks

**Comment by lucidNTR** [comment]
when i try to log in with a manually created accoutn kazana crashes

HTTP response 2015-11-06T15:51:51.820Z - 127.0.0.1 - OPTIONS /kazana/account/api/session 200 1ms
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at EventEmitter.emit (events.js:144:17)
    at EventEmitter.<anonymous> (/Users/jan/Entwicklung/eHealth/kazana/node_modules/npmlog/log.js:159:22)
    at EventEmitter.<anonymous> (/Users/jan/Entwicklung/eHealth/kazana/node_modules/npmlog/log.js:230:21)
    at logger (/Users/jan/Entwicklung/eHealth/kazana/node_modules/kazana-server/lib/plugins/logger.js:46:9)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Readable.push (_stream_readable.js:110:10)
    at Transform.push (_stream_transform.js:128:32)
    at internals.Squeeze._transform (/Users/jan/Entwicklung/eHealth/kazana/node_modules/good-squeeze/lib/squeeze.js:31:14)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/Users/jan/.node/bin/npm" "start"
npm ERR! node v4.2.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! @ehealthafrica/van@1.4.6 start: `grunt serve & kazana && fg`
npm ERR! Exit status 1

**Comment by gr2m** [comment]
can you try to update to latest `kazana` where the `Error: Uncaught, unspecified "error" event. ([object Object])` error stack issue is resolved? 

How did you sign up the manual user? Can you paste in the JSON here?

**Comment by lucidNTR** [comment]
i created a user in the user database 

{
   "_id": "org.couchdb.user:jan@example.com",
   "_rev": "3-fb815bd12b140dc28217a9bc0e770cd2",
   "name": "jan@example.com",
   "type": "user",
   "password_scheme": "pbkdf2",
   "iterations": 10,
   "roles": [
       "kazana-id:testadmin",
       "kazana-data-provider",
       "kazana-data-reviewer",
       "kazana-analyst",
       "kazana-admin",
       "van-data-provider",
       "van-data-reviewer",
       "van-analyst",
       "van-admin"
   ],
   "createdAt": "2015-04-15T00:00:00.000Z",
   "fullname": "Test Data Provider",
   "derived_key": "a584ea14732df52a11d1ff230fe4b2d1ce7d56f1",
   "salt": "878a9a897dc36fd4c713c8a9fd4a2c0e"
}

**Comment by lucidNTR** [comment]
(kazana update is in progress but requires a few npm dependency fixes ...)

**Comment by lucidNTR** [comment]
with current kazana the error is this:

Sill ops { event: 'ops',
Sill ops   timestamp: 1446832142771,
Sill ops   host: 'Wandervogel2.fritz.box',
Sill ops   pid: 64614,
Sill ops   os: 
Sill ops    { load: [ 2.31005859375, 2.39990234375, 2.7646484375 ],
Sill ops      mem: { total: 17179869184, free: 283058176 },
Sill ops      uptime: 795539 },
Sill ops   proc: 
Sill ops    { uptime: 31.861,
Sill ops      mem: { rss: 149467136, heapTotal: 112010752, heapUsed: 89879696 },
Sill ops      delay: 1.6165879964828491 },
Sill ops   load: 
Sill ops    { requests: { '5000': [Object] },
Sill ops      concurrents: { '5000': 4 },
Sill ops      responseTimes: { '5000': [Object] },
Sill ops      sockets: { http: [Object], https: [Object] } } }
HTTP response 2015-11-06T17:49:02.830Z - 127.0.0.1 - OPTIONS /kazana/account/api/session 200 3ms
Sill wreck { event: 'wreck',
Sill wreck   timestamp: 1446832142842,
Sill wreck   timeSpent: 3,
Sill wreck   pid: 64614,
Sill wreck   request: 
Sill wreck    { method: 'POST',
Sill wreck      path: '/_session',
Sill wreck      url: 'http://localhost:5984/_session',
Sill wreck      protocol: 'http:',
Sill wreck      host: 'localhost:5984',
Sill wreck      headers: 
Sill wreck       { 'content-length': '48',
Sill wreck         'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36',
Sill wreck         connection: 'keep-alive',
Sill wreck         referer: 'http://localhost:5000/',
Sill wreck         'accept-language': 'de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4',
Sill wreck         pragma: 'no-cache',
Sill wreck         'cache-control': 'no-cache',
Sill wreck         host: '127.0.0.1:5000',
Sill wreck         origin: 'http://localhost:5000',
Sill wreck         accept: 'application/json, text/plain, */*',
Sill wreck         'content-type': 'application/json;charset=UTF-8',
Sill wreck         'accept-encoding': 'gzip, deflate' } },
Sill wreck   response: 
Sill wreck    { statusCode: 200,
Sill wreck      statusMessage: 'OK',
Sill wreck      headers: 
Sill wreck       { 'set-cookie': [Object],
Sill wreck         server: 'CouchDB/1.6.1 (Erlang OTP/17)',
Sill wreck         date: 'Fri, 06 Nov 2015 17:49:02 GMT',
Sill wreck         'content-type': 'application/json',
Sill wreck         'content-length': '209',
Sill wreck         'cache-control': 'must-revalidate',
Sill wreck         'access-control-expose-headers': 'Cache-Control, Content-Type, Server',
Sill wreck         'access-control-allow-origin': 'http://localhost:5000',
Sill wreck         'access-control-allow-credentials': 'true' } } }
Sill error { event: 'error',
Sill error   timestamp: 1446832142835,
Sill error   id: '1446832142835:Wandervogel2.fritz.box:64614:ignyhf0l:10007',
Sill error   url: 
Sill error    Url {
Sill error      protocol: null,
Sill error      slashes: null,
Sill error      auth: null,
Sill error      host: null,
Sill error      port: null,
Sill error      hostname: null,
Sill error      hash: null,
Sill error      search: null,
Sill error      query: {},
Sill error      pathname: '/kazana/account/api/session',
Sill error      path: '/kazana/account/api/session',
Sill error      href: '/kazana/account/api/session' },
Sill error   method: 'post',
Sill error   pid: 64614,
Sill error   error: 
Sill error    { [not_found: missing]
Sill error      status: 404,
Sill error      name: 'not_found',
Sill error      message: 'missing',
Sill error      error: true,
Sill error      reason: 'missing',
Sill error      isBoom: true,
Sill error      isServer: true,
Sill error      data: null,
Sill error      output: { statusCode: 500, payload: [Object], headers: [Object] },
Sill error      reformat: [Function] } }

**Comment by gr2m** [comment]
I cannot reproduce the issue with https://github.com/eHealthAfrica/kazana-example. If I manually create a user, sign in, restart the server, I remain signed in as expected.

It might be an app-related issue. The `404 not found` issue might be related to a bug in pouchdb-server which has been resolved meanwhile (user cannot access own user doc). Can you make sure that you have kazana@8.0.1 installed for this app?

**Comment by lucidNTR** [comment]
kazana version is  8.0.1

**Comment by gr2m** [comment]
I could not reproduce the issue with the `van` repo, I did a fresh git cloned & npm install. Can you try to `rm -rf node_modules && npm install`?

**Comment by lucidNTR** [comment]
i removed node_modules and reinstalled. issue is the same.
could you send me your couchdb config? maybe there is something in my config that differs and could be the cause...

what i still dont understand is that you said you reproduced the bug already 5 days ago. (see above) are you sure you dont mix this issue up with something else? did you use the couchdb backend to test?

**Comment by gr2m** [comment]
Are you sure with the kazana dependency? `van` has currently `6.3.1` in its `pacakge.json`: https://github.com/eHealthAfrica/van/blob/master/package.json#L50

here's my couch.ini: https://gist.github.com/6ec90457975ae43f04af

Make sure to test the app in a private browser window. There is a problem if you sign in to CouchDb on the same host, even if the port number differs. Cookies are shared cross port numbers and I've seen that causing trouble in the past

**Comment by lucidNTR** [comment]
same in private window and when im logged out of couchdb.  i updated the kazana dependency locally...  now looking at the config file....

**Comment by lucidNTR** [comment]
still the same. i cant see things in the config that cause it i have the same cookie settings as you..

**Comment by gr2m** [comment]
for reference: https://issues.apache.org/jira/browse/COUCHDB-1356

**Comment by patriciagarcia** [comment]
@gr2m, can you please create follow up tasks and close this issue, thanks!

**Comment by jo** [comment]
Issue for correctly diff user docs: https://github.com/jo/couchdb-push/issues/25
